### ISSUE TITLE
Node connecting rules

### ISSUE THREAD

**Issue by gnud** [ONE-LOGIC/ngFlowchart#18]
What if have few types of nodes, a parent and child, and I want to put some rules what connectors can connect to what end points,

Is there an event handler or a way to do it ?

**Comment by PerFuchs** [comment]
There is a handler called `isValidEdge(sourceConnector, destinationConnector)` it gets the two connectors the user tries to connect and should return `true` if you allow the connection or `false` otherwise. Use the model to get the node for a given connector.

You might want to have a look at [this part of the readme](https://github.com/ONE-LOGIC/ngFlowchart#fc-canvas-attributes).

I maybe won't be able to answer during the next since days.

**Comment by gnud** [comment]
Sorry, I got it working, the issues was the callbacks attribute wasn't set in the fc-canvas directive :(.
So, no events were set.
